name=input("Please enter your name.")
print("Your name is " + name + ".")
print(type(name))
number=int(input("Please enter your favorite number."))
print("Your favorite number is " + str(number) + ".")
print(type(number))
activity=input("Please enter your favorite activity.")
print("Your favorite activity is " + activity + ".")
print(type(activity))
letter=input("Please enter your favorite letter.")
print("Your favorite letter is " + letter + ".")
print(type(letter))
work=input("Please enter what you do for work")
print("Your work is " + work + ".")
print(type(work))